In [3]:
class Demo:
    def test():
        print("test() for the class and method")
        return

In [4]:
class Demo:
    def test(self):
        print("test() for class and method")
        return
obj=Demo()
obj.test()

test() for class and method


In [8]:
class Demo1:
    def fact(self,n):
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
p1=Demo1()
print(p1.fact(5))

120


In [19]:
class Demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
            
    def add(self,p1,p2):
        return p1+p2
    
c1=Demo2(100,200)
print(c1.add(100,200))

300


In [20]:
lst=[1,2,3,4]
print(lst)


[1, 2, 3, 4]


In [26]:
import numpy as np
lst=[1,2,3,4]
array = np.array(lst)
print(array)


[1 2 3 4]


In [27]:
lst=[1,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int64


In [28]:
lst=[1.0,2.5,3.6,9.5]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
float64


In [33]:

import numpy as np
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [35]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [38]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [40]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [42]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [44]:
a1=np.array([(1,2,3),(4,5,6)]) 
print("slicing last column:",a1[:,2])



slicing last column: [3 6]


In [45]:
a1=np.array([(1,2,3),(4,5,6)])
print("first row:",a1[0])

first row: [1 2 3]


In [50]:
a1=np.array([(1,2,3),(4,5,6)])
print("second row:",a1[1])

second row: [4 5 6]


In [51]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing column:",a1[:,1])

slicing column: [2 5]


In [52]:
a1=np.array([(1,2,3),(4,5,6)])
print("row and column:",a1[1,:2])

row and column: [4 5]


In [56]:
import numpy as np
a1=np.random.normal(5,1,10)
print(a1)
print("Min value=",np.min(a1))
print("Max value=",np.max(a1))
print("Mean value=",np.mean(a1))
print("Median value=",np.median(a1))


[4.83645899 5.03133338 5.73498366 5.70428785 5.60691377 3.84759703
 4.92042507 4.44344384 6.00783896 2.14856229]
Min value= 2.148562294183014
Max value= 6.007838964209413
Mean value= 4.828184485660804
Median value= 4.975879225102242


In [57]:
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [60]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [61]:
b1=np.array([(1,5),(6,9)])
b2=np.array([(1,3),(1,6)])
np.dot(b1,b2)

array([[ 6, 33],
       [15, 72]])